"""
V6.5 아티스트 한글 이름 일괄 교정 스크립트
organic-graph.json의 영어 이름을 한글 공식명으로 교체합니다.
"""
import json

# 영문명 → 한글 공식명 매핑 (Seed 아티스트 중심, 주요 K-Culture 아티스트)
NAME_KO_MAP = {
    # ── 스크린샷에서 지적된 아티스트들 ──
    "Choi Jae Hoon": "최재훈",
    "An Jaewook": "안재욱",
    "Lee Ji Hyung": "이지형",
    "The Marshmallow Kisses": "더 마쉬멜로우 키세스",
    
    # ── Seed(depth=0) 아티스트 한글화 ──
    "BTS": "BTS",  # 국제공식명 유지
    "CNBLUE": "씨엔블루",
    "DJ DOC": "DJ DOC",
    "HYUN JIN YOUNG": "현진영",
    "In Kwon Jeon": "전인권",
    "Jang YoonJu": "장윤주",
    "Jeong Hongil": "정홍일",
    "Junesun Kim": "김준선",
    "Kim Hyun Jung": "김현정",
    "Kim Hyun Woo": "김현우",
    "Kim Jang-Hoon": "김장훈",
    "Kim Jung Mi": "김정미",
    "Kim Kyung Ho": "김경호",
    "Kim Minwoo": "김민우",
    "Kim SangMin": "김상민",
    "Kim Soo Cheol": "김수철",
    "Kim Tae Hwa": "김태화",
    "Kim Tae Hyun": "김태현",
    "Kim Won Jun": "김원준",
    "KIM sung myun": "김성면",
    "KYUNGHO BANG": "방경호",
    "Kang Sunghee": "강성희",
    "Kyunghwa Jung": "정경화",
    "Lee Duke Jean": "이덕진",
    "Lee Jeong Seon": "이정선",
    "Lee Ji Hoon": "이지훈",
    "Lee Sang Eun": "이상은",
    "Lee Sang Woo": "이상우",
    "Lee Yerin": "이예린",
    "LEE HYUN SUK PROJECT": "이현석 프로젝트",
    "LEEHEESANG": "이희상",
    "Min Hae Kyung": "민해경",
    "No Sa Yeon": "노사연",
    "Park Hye Kyung": "박혜경",
    "Park Jungwoon": "박정운",
    "Ryu JiHo": "류지호",
    "Seo Ji Won": "서지원",
    "Shin Hyobum": "신효범",
    "Shin In Ryu": "신인류",
    "Shin Joong Hyun And Musicpower": "신중현과 뮤직파워",
    "TAE JIN AH": "태진아",
    "Cho Jang Hyuck": "조장혁",
    "Choi Min woo": "최민우",
    "Choi Yong Jun": "최용준",
    "Chuli & Miae": "철이와 미애",
    "huijun woo": "우희준",
    "jo dongik": "조동익",
    "Shim Shin": "심신",
    "Lang Lee": "이랑",
    
    # ── 밴드/그룹 ──
    "015B": "공일오비",
    "1TYM": "원타임",
    "NRG": "NRG",
    "R.ef": "R.ef",
    "S.E.S.": "S.E.S.",
    "Clon": "클론",
    "Songolmae": "송골매",
    "Sinchon Blues": "신촌블루스",
    "Novasonic": "노바소닉",
    "Soombee": "숨비",
    "Loveholics": "러브홀릭",
    "Rollercoaster": "롤러코스터",
    "Galaxy Express": "갤럭시 익스프레스",
    "DELISPICE": "델리스파이스",
    "Glen Check": "글렌체크",
    "GgoiJjaDeul": "꽃자들",
    "Yangpa": "양파",
    "Zion.T": "자이언티",
    "ZoPD": "조PD",
    "Broken Valentine": "브로큰 발렌타인",
    "Sultan of the Disco": "술탄 오브 더 디스코",
    "Panic": "패닉",
    "YB": "윤도현밴드",
    "The Cross": "더 크로스",
    "The Rose": "더 로즈",
    "The Volunteers": "더 볼런티어스",
    "SURL": "설",
    "Mid-Air Thief": "공중도둑",
    "Parannoul": "파란노을",
    "HAEPAARY": "해파리",
    "HANRORO": "한로로",
    "JEONGMILLA": "정밀아",
    "Bosudongcooler": "보수동쿨러",
    "Hwal Band": "활",
    "Hexagonal Water": "육각수",
    "Soumbalgwang": "소음발광",
    "Noizegarden": "노이즈가든",
    "Gate Flowers": "게이트 플라워즈",
    "Moonlight Fairy Reversal Grand Slam": "달빛요정역전만루홈런",
    "Life and Time": "라이프 앤 타임",
    "Switcbak": "스위치백",
    "Yangbans": "양반들",
    "KIRARA": "키라라",
    "NOVADOX": "노바독스",
    "FAKE UNIVERSE": "페이크 유니버스",
    "HERD": "HERD",
    "Underwears Band": "언더웨어즈",
    "Yellow Monsters": "옐로 몬스터즈",
    "TRPP": "TRPP",
    "RAW BY PEPPERS": "RAW BY PEPPERS",
    "Goodmorning Pancake": "굿모닝 팬케이크",
    "Three Strangers": "세명의 이방인",
    "ROCK-TA PROJECT BAND": "록타 프로젝트 밴드",
    "Knave": "네이브",
    "Redoor": "레도어",
    "Five Sense": "파이브 센스",
    "Lustrouble": "러스트러블",
    "Leaves Black": "리브스 블랙",
    "OWALLOIL": "오왈로일",
    "Loro's": "로로스",
    "Mr Miss": "미스터미스",
    "TwoTwo": "투투",
    "BADLAMB": "배드램",
    "Budung": "부등",
    "Y2K": "Y2K",
    "pH-1": "pH-1",
    "9 and the Numbers": "구와 더 넘버즈",
    "1415": "1415",
    "Adios Audio": "아디오스 오디오",
    "Hyunyi with Cinderella": "현이와 신데렐라",
    "Aurora Ave.": "오로라 애비뉴",
    "B612": "B612",
    "Black Hole": "블랙홀",
    "Bob James": "Bob James",
    "Breeze": "브리즈",
    "SSaW": "SSaW",
    "CRASH": "크래쉬",
    "Circle": "써클",
    "Charlie jung Band": "찰리정밴드",
    "ROUND TABLE": "라운드 테이블",
    "ADORA": "아도라",
    "YEREMY": "예레미",
    "YTC": "YTC",
    "Satellite Lovers": "새틀라이트 러버즈",
    "oomool": "오무울",
    "Runway": "런웨이",
    "Falcon": "팔콘",
    "Genie": "지니",
    "Harlequin": "할리퀸",
    "H2O": "H2O",
    "Minuano": "미누아노",
    "Phonebooth": "폰부스",
    "Pinocchio": "피노키오",
    "Untitle": "언타이틀",
    "Yarn": "얀",
    "Zam": "잠",
    "Bank": "뱅크",
    "153/Joombas": "153/줌바스",
    "The MD": "더 MD",
    "The Monotones": "더 모노톤즈",
    "The Poles": "더 폴즈",
    "The Green Tea": "더 그린티",
    "The Breeze": "더 브리즈",
    "Tuesday Beach Club": "화요비치클럽",
    "90TAN": "90탄",
    "Magma": "마그마",
    "3RACHA": "쓰리라차",
    "5RACHA": "파이브라차",
    "jisokuryClub": "지속류클럽",
    "rourourourous": "루루루러스",
    "metro trip": "메트로 트립",
    
    # ── 일본/해외 아티스트는 영문 유지 ──
    "Cibo Matto": "Cibo Matto",
    "Miharu Koshi": "Miharu Koshi", 
    "Saeko Inuzuka": "Saeko Inuzuka",
    "Saki Takaoka": "Saki Takaoka",
    "Takaki Horigome": "Takaki Horigome",
    "naomi & goro": "naomi & goro",
    "mamerico": "mamerico",
    "pomodorosa": "pomodorosa",
    "sugar plant": "sugar plant",
    
    # ── 비시드(depth>0) 주요 한국 아티스트 ──
    "IU": "아이유",
    "Baek A": "백아",
    "The Black Skirts": "검정치마",
    "BLACKPINK": "BLACKPINK",
    "AKMU": "악동뮤지션",
    "EXO": "엑소",
    "BIGBANG": "빅뱅",
    "TWICE": "트와이스",
    "SEVENTEEN": "세븐틴",
    "G-DRAGON": "지드래곤",
    "ZICO": "지코",
    "TAEYEON": "태연",
    "E SENS": "이센스",
    "WINNER": "위너",
    "iKON": "아이콘",
    "GOT7": "갓세븐",
    "Red Velvet": "레드벨벳",
    "NCT 127": "NCT 127",
    "NCT DREAM": "NCT DREAM",
    "ITZY": "있지",
    "aespa": "에스파",
    "Stray Kids": "스트레이 키즈",
    "LE SSERAFIM": "르세라핌",
    "NewJeans": "뉴진스",
    "MAMAMOO": "마마무",
    "GFriend": "여자친구",
    "MONSTA X": "몬스타엑스",
    "TXT": "투모로우바이투게더",
    "ATEEZ": "에이티즈",
    "Apink": "에이핑크",
    "ASTRO": "아스트로",
    "Brown Eyed Girls": "브라운아이드걸스",
    "Brown Eyes": "브라운아이즈",
    "Brown Eyed Soul": "브라운아이드소울",
    "Fly to the Sky": "플라이 투 더 스카이",
    "SHINee": "샤이니",
    "f(x)": "에프엑스",
    "Girls' Generation": "소녀시대",
    "Super Junior": "슈퍼주니어",
    "Wonder Girls": "원더걸스",
    "miss A": "미쓰에이",
    "2PM": "투피엠",
    "2AM": "투에이엠",
    "Beast": "비스트",
    "Block B": "블락비",
    "INFINITE": "인피니트",
    "T-ara": "티아라",
    "4Minute": "포미닛",
    "AOA": "AOA",
    "VIXX": "빅스",
    "B.A.P": "비에이피",
    "BTOB": "비투비",
    "EXID": "이엑스아이디",
    "Lovelyz": "러블리즈",
    "Oh My Girl": "오마이걸",
    "WJSN": "우주소녀",
    "Pentagon": "펜타곤",
    "Day6": "데이식스",
    "Dreamcatcher": "드림캐쳐",
    "EVERGLOW": "에버글로우",
    "CIX": "씨아이엑스",
    "Cherry Bullet": "체리블렛",
    "Brave Girls": "브레이브걸스",
    "H.O.T.": "H.O.T.",
    "Sechs Kies": "젝스키스",
    "g.o.d": "god",
    "Rain": "비",
    "BoA": "보아",
    "Lee Hyori": "이효리",
    "Psy": "싸이",
    "TVXQ": "동방신기",
    "KARA": "카라",
    "After School": "애프터스쿨",
    "Nine Muses": "나인뮤지스",
    "Hello Venus": "헬로비너스",
    "Sistar": "씨스타",
    "MOMOLAND": "모모랜드",
    "Wanna One": "워너원",
    "X1": "엑스원",
    "IZ*ONE": "아이즈원",
    "fromis_9": "프로미스나인",
    "Kep1er": "케플러",
    "NMIXX": "엔믹스",
    "ENHYPEN": "엔하이픈",
    "Billlie": "빌리",
    "CLASS:y": "클라씨",
    "(G)I-DLE": "여자아이들",
    "TREASURE": "트레저",
    "TEMPEST": "템페스트",
    "VERIVERY": "베리베리",
    "THE BOYZ": "더보이즈",
    "ONEUS": "원어스",
    "ONEWE": "원위",
    "N.Flying": "엔플라잉",
    "SF9": "에스에프나인",
    "Golden Child": "골든차일드",
    "ONF": "온앤오프",
    "AB6IX": "에이비식스",
    "cravity": "크래비티",
    "MCND": "엠시엔디",
    "DRIPPIN": "드리핀",
    "WEi": "위아이",
    "Epik High": "에픽하이",
    "Dynamic Duo": "다이나믹 듀오",
    "Verbal Jint": "버벌진트",
    "Simon Dominic": "사이먼 도미닉",
    "Beenzino": "빈지노",
    "Crush": "크러쉬",
    "Dean": "딘",
    "Heize": "헤이즈",
    "SUNMI": "선미",
    "Chungha": "청하",
    "Hwasa": "화사",
    "Wendy": "웬디",
    "Baekhyun": "백현",
    "Kai": "카이",
    "D.O.": "디오",
    "Sehun": "세훈",
    "Chanyeol": "찬열",
    "Chen": "첸",
    "Suho": "수호",
    "Lay": "레이",
    "Xiumin": "시우민",
    "Jackson Wang": "잭슨",
    "JEON SOMI": "전소미",
    "SUNMI": "선미",
    "HyunA": "현아",
    "Taemin": "태민",
    "Key": "키",
    "Onew": "온유",
    "Minho": "민호",
    "Jay Park": "박재범",
}

with open('scripts/.cache/v5.4/organic-graph.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

updated = 0
for node in data['nodes']:
    name = node.get('name', '')
    current_ko = node.get('nameKo', '')
    
    if name in NAME_KO_MAP:
        new_ko = NAME_KO_MAP[name]
        if current_ko != new_ko:
            node['nameKo'] = new_ko
            updated += 1

print(f"한글화 교정 완료: {updated}개 노드 업데이트")

with open('scripts/.cache/v5.4/organic-graph.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("organic-graph.json 저장 완료")
